name = "wadaxi"
main = "_worker.js"
compatibility_date = "2023-10-11"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "guestbook-db"
database_id = "14b03b98-a188-4e05-ba67-073d879e3779"

# 环境变量
[vars]
NODE_ENV = "production"
PAGES_URL = "https://guestbook-static.pages.dev"  # 更新为您的 Pages URL

# 开发服务器配置
[dev]
port = 8787
local_protocol = "http"