name = "guestbook"
compatibility_date = "2023-10-13"
pages_build_output_dir = "."

# 开发环境配置
[dev.vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
ADMIN_API_KEY = "6caa82d8c83cd38d66fb92944c75367b7bddece4f5a2a6d1f7794b0ad9ce1f92"
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""

# 开发环境数据库配置
[dev.d1_databases]
DB = { database_name = "guestbook", database_id = "5ebf843d-0f4c-4862-8d94-7e51af0989a7" }

# 生产环境配置
[env.production]
# 环境变量（通过 Cloudflare 仪表板设置）
ADMIN_USERNAME = ""
ADMIN_PASSWORD = ""
ADMIN_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""

# 生产环境数据库配置
[env.production.d1_databases]
DB = { database_name = "guestbook", database_id = "5ebf843d-0f4c-4862-8d94-7e51af0989a7" }