name = "guestbook"
compatibility_date = "2023-10-11"
pages_build_output_dir = "."

# 环境变量
[vars]
# 默认环境变量（开发环境）
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
ADMIN_API_KEY = "your-api-key-here"

# 生产环境变量（通过 Cloudflare 仪表板设置）
[env.production]
# 这些变量需要在 Cloudflare 仪表板中设置为环境变量
# ADMIN_USERNAME = ""
# ADMIN_PASSWORD = ""
# ADMIN_API_KEY = ""
