name = "guestbook"
compatibility_date = "2023-10-13"
pages_build_output_dir = "."

# 开发环境变量
[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"
ADMIN_API_KEY = "6caa82d8c83cd38d66fb92944c75367b7bddece4f5a2a6d1f7794b0ad9ce1f92"

# 生产环境变量（通过 Cloudflare 仪表板设置）
[env.production]
ADMIN_USERNAME = ""
ADMIN_PASSWORD = ""
ADMIN_API_KEY = ""
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""
SUPABASE_SERVICE_ROLE_KEY = ""