name = "guestbook-api"
main = "src/worker.js"
compatibility_date = "2023-05-18"

[[d1_databases]]
binding = "DB" # 在 Worker 中使用的变量名
database_name = "guestbook-db" # 在 Cloudflare 控制台中创建的数据库名称
database_id = "YOUR_DATABASE_ID" # 替换为您的数据库 ID

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

# CORS 配置
[[headers]]
for = "*"

[[headers.values]]
key = "Access-Control-Allow-Origin"
value = "*"

[[headers.values]]
key = "Access-Control-Allow-Methods"
value = "GET, POST, PUT, DELETE, OPTIONS"

[[headers.values]]
key = "Access-Control-Allow-Headers"
value = "Content-Type, Authorization"
